### ISSUE TITLE
Cross link to other language implementations

### ISSUE THREAD

**Issue by stereobooster** [keon/algorithms#10]
Something like [Rosetta Stone](https://en.wikipedia.org/wiki/Rosetta_Stone) for [code](http://rosettacode.org/wiki/Category:Programming_Tasks).

[Similar repo in ruby](https://github.com/sagivo/algorithms).

**Comment by qkraudghgh** [comment]
Nice Idea
and I'm rewriting it in the golang
check [this repo](https://github.com/qkraudghgh/algorithms)
Thx.

**Comment by marcosfede** [comment]
Inspired by your repo, I started solving the problems myself and building implementations in many other languages. Here is a [Link to my repository](https://github.com/marcosfede/algorithms).
Regards

**Comment by kurianCoding** [comment]
Implementing it in Golang, along with some more algorithms that I find int the website geeksforgeeks
[this](https://github.com/kurianCoding/g4g) is the repo.
