### ISSUE TITLE
Character encoding issue with heap/skyline.py

### ISSUE THREAD

**Issue by eliotpearson** [keon/algorithms#119]
Running on python 2.7 on Mac High Sierra I get the following error.

```
 python skyline.py 
  File "skyline.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file skyline.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by jadhavmanoj** [comment]
getting the same error. I resolved it by adding file encoding as utf-8. at the top of the file. 
`# -*- coding: utf-8 -*-`. 

@keon let me know if this is good practice.

**Comment by keon** [comment]
Sure. But I recommend using Python 3 in the first place.

**Comment by eliotpearson** [comment]
@keon is the project only supporting Python 3 officially?  Most Macs are rolling with 2.7.  I understand if 3 is the standard.
