### ISSUE TITLE
Non-Python code

### ISSUE THREAD

**Issue by delirious-lettuce** [keon/algorithms#15]
> Minimal examples of data structures and algorithms in Python

Despite ending with `.py`, neither of these files have Python code in them.

* [make_sentence.py](https://github.com/keon/algorithms/blob/master/string/make_sentence.py)
* [combination_sum.py](https://github.com/keon/algorithms/blob/master/dp/combination_sum.py)

**Comment by keon** [comment]
yup. I gotta convert that to Python.
Thanks for the reminder

**Comment by delirious-lettuce** [comment]
No problem! I'm actually just about to send you a PR for a different file in this repo.
