### ISSUE TITLE
separate test module

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#162]
Since we now have tests in most of the algorithms, I think it is a good idea to have a separate `test_module.py` file in each module. We can move all the tests from one module to it, and any further algorithms must have their tests in this file. It will make the repo easy to manage.
@keon what do you think? I can start working on this.

**Comment by christianbender** [comment]
@goswami-rahul 
The problem is that we have not in all projects unit tests. Many projects (that I have see) have simple tests with the ```print``` function that prints something on the console. The idea with the central test-file sounds good.

**Comment by goswami-rahul** [comment]
yeah those print statements need to be changed to tests too.  
But there is one disadvantage in moving tests to separate file, that the tests at the same place can also help viewers understand the algorithms better.

**Comment by christianbender** [comment]
@goswami-rahul  I will jump in.

**Comment by christianbender** [comment]
@goswami-rahul @keon 
I will test the module ```maths```.  I add a file ```test_module.py``` with all tests.

**Comment by goswami-rahul** [comment]
@christianbender I would wait for starting work on this until @keon approves on this issue.

**Comment by christianbender** [comment]
@goswami-rahul  OK, I will wait. Thanks for the notice

**Comment by christianbender** [comment]
@danghai At the moment I pause on my work on this task. Because we don't have an approval.

**Comment by keon** [comment]
@christianbender 

sorry for the late reply :(
As the repo gets larger, separating test code may be more scalable.
Let's give it a shot and see if it works better!

**Comment by christianbender** [comment]
@keon @goswami-rahul #220
