### ISSUE TITLE
Repo Python version?

### ISSUE THREAD

**Issue by delirious-lettuce** [keon/algorithms#17]
This repo doesn't seem to be consistent about which version of Python the code is written for.

* Some files use type hints (`SyntaxError` in Python 2)
* Some files use `print` statements (`SyntaxError` in Python 3)
* [garage.py](https://github.com/keon/algorithms/blob/master/array/garage.py) has a mix of `print` statements and `print` as a function (although Python 2 doesn't treat it as a function)

I guess my question is, which version(s) of Python is this repo supposed to be for?

Importing `__future__.print_function` and adding brackets to all the `print` statements is fairly easy, but the type hinting is Python 3 only (although they could be moved to the docstrings for cross-compatibility).

**Comment by keon** [comment]
I think we should make it consistent for Python 3.5+

**Comment by delirious-lettuce** [comment]
@keon ,

It would probably be better to be more explicit about the target Python version(s) in the repository description and `README`.

The only "issue" with the repository being 3.5+ is that the examples then can't use fstrings (since they are 3.6+ only). That's a decision you'll have to make.

---
Also, I'm not sure that type hints (as function annotations) should be used in the examples since it seems to contradict your own description.

>  "Minimal examples of data structures and algorithms in Python"

Since type hints (as function annotations) are optional and essentially ignored by Python, adding them doesn't seem to show "minimal" examples of Python code. Adding type hints to the docstrings would give the same amount of information but would also adhere to the repos stated goal of "minimal examples".

> ["It should also be emphasized that Python will remain a dynamically typed language, and the authors have no desire to ever make type hints mandatory, even by convention."](https://www.python.org/dev/peps/pep-0484/#non-goals)

Again, these decisions are up to you!

**Comment by keon** [comment]
@delirious-lettuce thanks for the good points!
I really like fstrings... but I am not sure what % of python users use 3.6. I guess the majority still uses 3.5. 
Though I think it shouldn't matter since this repo is going to be a stand-alone project for learning purposes.

Yeah, I think it's better to switch to docstrings. Many are more familiar with it and many IDEs still don't recognize type hinting in Python.

**Comment by delirious-lettuce** [comment]
@keon ,

As much as I also like `fstrings`, I think you are correct that many people are still using Python 3.5.
