### ISSUE TITLE
What does this algorithm do?

### ISSUE THREAD

**Issue by christianbender** [keon/algorithms#181]
@keon @goswami-rahul 

[nth_digit.py](https://github.com/keon/algorithms/blob/master/maths/nth_digit.py)
In this file is the function ```find_nth_digit(n)```  
At the moment I ponder what this function does do?  
The explanation of the author helps me not.  

**Tests:** At the moment I wrote tests for the module ```maths```

**Comment by keon** [comment]
@christianbender 
I think it came from this one: https://leetcode.com/problems/nth-digit/description/
an interesting problem.

**Comment by goswami-rahul** [comment]
@keon @christianbender I found a similar, a bit difficult problem yesterday which was generalised for any base `2<=b<=10`, and had range query for a single digit. Any ideas on [this problem](https://www.hackerearth.com/practice/algorithms/dynamic-programming/2-dimensional/practice-problems/algorithm/killjee-and-infinite-string-beae8adf/)?

**Comment by christianbender** [comment]
@keon Thanks for the informations. 

@goswami-rahul  I will see it.
