### ISSUE TITLE
what does linkedlist/copy_random_pointer.py do?

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#187]
[copy_random_pointer.py](https://github.com/keon/algorithms/blob/master/linkedlist/copy_random_pointer.py)  
has badly written description and code. Don't know what this does?
@christianbender @keon

**Comment by keon** [comment]
hmm. i don't remember but when I search it on google, this shows up: https://leetcode.com/problems/copy-list-with-random-pointer
