### ISSUE TITLE
Anagram.py defines all_perms method twice

### ISSUE THREAD

**Issue by eliotpearson** [keon/algorithms#21]
Not sure if this was intended, but the code doesn't seem to access the first all_perms function.

https://github.com/keon/algorithms/blob/0ef4b7409a1480b0522da04e9952a732fb76b4c4/backtrack/anagram.py#L1-L17

**Comment by ankit167** [comment]
Looks like different versions of the same function is written (one to demonstrate yield, and the other to demonstrate return). Clearly, one of the functions should exist, If not, the name of the functions can be changed.

**Comment by delirious-lettuce** [comment]
I'm curious as to why @keon didn't use `itertools.permutations` for `all_perms`?

```python
from itertools import permutations


def all_perms(s):
    return [''.join(p) for p in permutations(s)]


if __name__ == '__main__':
    assert all_perms('abc') == ['abc', 'acb', 'bac', 'bca', 'cab', 'cba']
```

The current implementation of `all_perms` seems very inefficient and not very "Pythonic".

---
Also, the `anagram` function itself is written in an odd way as well. Using `collections.Counter` is much easier.

```python
# Version 1
>>> from collections import Counter
>>> Counter('apple') == Counter('pleap')
True

# Version 2
>>> sorted('apple') == sorted('pleap')
True

```

**Comment by keon** [comment]
@delirious-lettuce 
hmm.. that was to show the inner workings of permutation.
if we just use permutation function it defeats the purpose. But them I guess it becomes not so pythonic. So why don't we keep the generator version. The one-liner version using permutation function can go into `docstring`.

Your `Counter` trick for anagram is awesome. Let's also put that into the `docstring`.
