### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by keon** [keon/algorithms#210]
As the repo grows rapidly, I believe we need more hands on fixing code and reviewing PR.
I recommend @danghai and @SaadBenn to become our new maintainers since they contributed a lot lately.

What do you guys think?
@goswami-rahul @christianbender

**Comment by christianbender** [comment]
Yeah, of course. Then I can work on #162  (we wait of your approval, keon?)

**Comment by goswami-rahul** [comment]
Yes, it is a good decision. More active maintainers will help the repo grow faster :)

**Comment by keon** [comment]
Welcome :)
I am in NYC by the way.
