### ISSUE TITLE
Please avoid directly commit to master

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#218]
A quick reminder to the newer collaborators :)
Please avoid directly committing to this repo. It is always a good idea and practice to open a PR for any change ( adding an algorithm or modifing something). In this way, other collaborators can review and suggest changes, which will be more helpful for the repo.  This will also let identify errors and avoid merges to the main repo causing errors like this one [like this one](https://travis-ci.org/keon/algorithms/builds/365395260?utm_source=github_status&utm_medium=notification).  
@SaadBenn @danghai @christianbender

**Comment by SaadBenn** [comment]
It was my mistake, I'll be careful next time.

**Comment by christianbender** [comment]
@goswami-rahul @SaadBenn @danghai 
Maybe we should notice this in the [CONTRIBUTING.md](https://github.com/keon/algorithms/blob/master/CONTRIBUTING.md) . And should this file link in the README.md. Right away in the head.

**Comment by danghai** [comment]
@SaadBenn 
Please do not commit with the general name (Ex: `Update README.md`). Writing a good specific commit makes other people easy to follow and know what you do in your commit. It also helps people keep track of information about these commit later when they want to review

**Comment by SaadBenn** [comment]
I'll make sure of that. @danghai

**Comment by SaadBenn** [comment]
I was thinking that we are making one too many commits for each algorithm or test that we submit. Is it possible to squash it to maybe just a single commit/ file unless the commit is very specific then in that case we can have that. Another issue that I found was that our git history is very non-linear. There is a lot of bubbles in our git history which makes it impossible to follow. The solution is very simple: Once we create a branch and make our changes, all we need is rebase our branch against the local master and once we have that then we can push our changes from the master to the repo's master. That way our history would become linear and much more elegant. Just my two cents tho.

**Comment by keon** [comment]
@goswami-rahul @christianbender @danghai @SaadBenn 
I agree with @SaadBenn . If possible please squash the commits so that it is easier to see what individual commits are for.
I'll close the issue.
