### ISSUE TITLE
bugs in math/rsa.py

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#226]
math/rsa.py sometimes shows up an error which means it still has some bugs. It passed previous tests because the data for rsa test is generated randomly, due which like it fails sometimes. This need to be fixed!
https://travis-ci.org/keon/algorithms/builds/366117956
when I restarted build, the test was passed.

**Comment by christianbender** [comment]
@goswami-rahul 
I thought I had fixed the bug. I added ```random.seed()``` in the function ```def genprime(k):``` in the file rsa.py

**Comment by christianbender** [comment]
@goswami-rahul 
I think the encryption level is to low with 8 bits.I wrote a new test with encryption level ```26 bits```. The test runs 100 times successful! If I minimize the encryption level the test fails! 

The original author used a encryption level of 1024 bits! On my machine a encryption level of 32 bits already  takes a while! 1024 bits for me impossible.

**Comment by goswami-rahul** [comment]
@christianbender yes I changed some parameters of generate_key(). I added an optional argument `seed` which would help in testing. I also rewrote `is_prime` inside it, instead of importing from `rabin_miller` to resolve ambuiguity in #227 .

**Comment by christianbender** [comment]
@goswami-rahul Can we close this issue?
