### ISSUE TITLE
Bit Manipulation: Some interesting questions

### ISSUE THREAD

**Issue by danghai** [keon/algorithms#241]
1) **Flip Bit to win:** You have an integer and you can flip exactly one bit from a `0` to `1`. Write code to find the length of the longest sequence of `1s` you could create. 
For example:
Input: 1775 ( or: `11011101111`)
Output: 8 

2) **Conversion:** Write a function to determine the number of bits you would need to flip to convert integer A to integer B.
For example:
Input:  29 (or: `11101`), 15 (or: `01111`)
Output: 2

**Comment by goswami-rahul** [comment]
Not sure about the first problem, but the second problem can be solved by first taking the `xor` of the two numbers, and then count the number of set bits in it.

**Comment by SaadBenn** [comment]
Those are very interesting questions. @danghai 
Bit manipulation is something that I lack.

**Comment by danghai** [comment]
@SaadBenn I create some questions in bit manipulation in PR #253 (It does not contain 2 questions in this issue). You can contribute by adding more algorithm to solve the problem, or get more bit manipulation question.

**Comment by SaadBenn** [comment]
@danghai Thanks. I'll get back to adding more algorithms but at the moment I've some big assignments going on.
