### ISSUE TITLE
Write all test case for string: test_string.py in tests

### ISSUE THREAD

**Issue by danghai** [keon/algorithms#246]

**Comment by christianbender** [comment]
@danghai I will write tests for the module ```strings```. But how can I move this file in the directory ```tests``` and run the tests in it?

**Comment by danghai** [comment]
@christianbender I have updated the `README.md` about how to test all module, or how to test a specific module

**Comment by danghai** [comment]
No, you are not. You just miss updated information.

**Comment by christianbender** [comment]
@danghai  Done #255
