### ISSUE TITLE
Tests in directory tests 

### ISSUE THREAD

**Issue by christianbender** [keon/algorithms#247]
[tests](https://github.com/keon/algorithms/tree/master/tests)  
If I ran the tests I get this kind of error message:  

> from search.binary_search import binary_search, binary_search_recur
ImportError: No module named 'search'

or   

> from array.delete_nth import delete_nth, delete_nth_naive
ImportError: No module named 'array.delete_nth'; 'array' is not a package

**Comment by goswami-rahul** [comment]
@christianbender I think there is no `__init__.py` file in `array` and `search` module yet, that is why it is not recognized as a package.

**Comment by danghai** [comment]
Hello @christianbender , could you give exact the command makes these error. 
btw, you miss the `__init__` in maths

**Comment by danghai** [comment]
Thanks, that is all I am looking for

**Comment by goswami-rahul** [comment]
@christianbender are you sure your branch is currently updated with the original repo?
Because your master branch is currently 220 commits behind this repo. Please update your fork, and try again if this error still shows up.

**Comment by christianbender** [comment]
@goswami-rahul  My local branch on my machine is up to date. 
@danghai 
 > Hello @christianbender , could you give exact the command makes these error.
btw, you miss the __init__ in maths

I tried to ran any file. But this error (above) occures. In the example above I tried to ran the file ```test_search.py``` and the file ```test_array.py```.

**Comment by danghai** [comment]
@christianbender  what is your command line?

**Comment by christianbender** [comment]
@danghai @goswami-rahul  I'm a idiot! :angry: I started the files seperated ... :flushed: Now with the command ```python3 -m unittest discover tests``` it works perfect! :smirk:
