### ISSUE TITLE
in tree.bst.delete_node self.deleteNode is not defined

### ISSUE THREAD

**Issue by Njsao** [keon/algorithms#257]
https://github.com/keon/algorithms/blob/master/tree/bst/delete_node.py

at line 63 and 65 the function deletenode is called.
This method does not exist, maybe a recursive call of delete_node was meant?

**Comment by danghai** [comment]
Hi @Njsao I think they write your code and test on leetcode. Could you remove `class Solution(object):` , and remove `self` in method? 
What is your plan on testing these function by using `unittest`?

**Comment by Njsao** [comment]
Hi @danghai I have already forked and written some unittest:
https://github.com/Njsao/algorithms/tree/test_tree
What do you think about?

**Comment by danghai** [comment]
Hello @Njsao, I put my comment in your commit.

**Comment by Njsao** [comment]
I read your comments @danghai. I will refractor those changes before the pull request
