### ISSUE TITLE
Need a translation in Korean

### ISSUE THREAD

**Issue by KSH-code** [keon/algorithms#275]

**Comment by keon** [comment]
I could do that.
stay tuned!

**Comment by christianbender** [comment]
@keon I can write a translation in german. Would be nice... In Germany exists many Pythonists :D

**Comment by keon** [comment]
@christianbender sure, sounds great !

**Comment by christianbender** [comment]
@keon Done. I added a german readme.

**Comment by keon** [comment]
Closing as translations are added thanks guys!
