### ISSUE TITLE
Organizing the repo neatly

### ISSUE THREAD

**Issue by SaadBenn** [keon/algorithms#278]
Hey guys, I was wondering we should put all the algorithms in an `algorithm` folder or something. I feel like It's getting big with all those new files being added to it. I have to scroll all the way down or up to get to where I want and right now I feel it is a bit disorganized. It would be very easy for readers to just click the `algorithm` folder and look for the intended algorithms inside it. The extra junk can remain outside. What do you guys think?

**Comment by danghai** [comment]
I mentioned it in #264 to handle python packaging to avoid conflict the core's library python by put all folder under `algorithms`. We are going to wait for Keon's approval. But it requires update a lot README, import, ...

**Comment by keon** [comment]
@danghai @SaadBenn I am going to be able to work on this after friday.
But feel free to work on it ahead :)

**Comment by christianbender** [comment]
@SaadBenn Do you mean a directory for each problem set?

**Comment by SaadBenn** [comment]
Oh no that'd make it more congested. What I meant was put everything that we have in an `algorithm` folder and by everything I mean just the algorithms that we have. So `ReadME` and all those other files can stay outside. @christianbender

**Comment by SaadBenn** [comment]
BTW I'm extremely busy with my semester so please bear with me. I'll start working on this repo ASAP.

**Comment by keon** [comment]
I'm forever done with my school now. I'm on it :)

**Comment by SaadBenn** [comment]
Congratulations!! You're one lucky guy. @keon

**Comment by danghai** [comment]
Sorry for late response, what do you think @keon about idea's @SaadBenn ?
