### ISSUE TITLE
Does anyone know how to set up Travis for java?

### ISSUE THREAD

**Issue by SaadBenn** [keon/algorithms#282]
I know this may not the right place to ask this question but I am working on an Android Studio project and am not very familiar with Travis. All I want is to catch syntax errors and undefined names.

I am asking this questions because the travis for this repo does this nicely. However, I'll be working with Java and was wondering anyone with better understanding could point me in the right direction?

@danghai @keon you guys seem to be familiar with travis.

BTW sorry for asking questions not related to the repo but I have been super busy lately with projects and stuff.

**Comment by danghai** [comment]
@SaadBenn https://docs.travis-ci.com/user/getting-started/ is a good link

**Comment by SaadBenn** [comment]
Thanks @danghai I looked into that but that doesn't explain how to catch syntax errors. Plus my project is on Gitlab and travis doesn't support gitlab. I am looking for other options.

**Comment by danghai** [comment]
@SaadBenn You can read some `travis` file from Java trending on github. It is really useful too.

**Comment by keon** [comment]
Sorry, I don't use Java.
