### ISSUE TITLE
installing algorithms also installs tests

### ISSUE THREAD

**Issue by goswami-rahul** [keon/algorithms#350]
while installing through `pip install algorithms`, the `tests/` module also gets installed. I don't know if this will be of any use to the end-users. I think we can exclude this from getting packaged.  
Even if we want to package it with the install, the current api is 
```python
from tests import test_arrays
```
It should be inside the algorithms folder, to be explicit that these tests belong to algorithms, more like
```python
from algorithms.tests import test_arrays
```
What do you think @keon @danghai ?

**Comment by danghai** [comment]
In my opinion, I think test is not api. So the user do not need to import test.

**Comment by goswami-rahul** [comment]
Yeah, I guess we can remove `tests/*` from the MANIFEST.in then?

**Comment by danghai** [comment]
@goswami-rahul I am not sure why I cannot import `tests`

**Comment by danghai** [comment]
Yeah @goswami-rahul, removing `tests/*` from the MANIFEST.in is a solution.

**Comment by keon** [comment]
thanks for spotting this problem.
and yeah it must be fixed.
