### ISSUE TITLE
combination.py large number n, r case too slow to find a combination

### ISSUE THREAD

**Issue by arsgsg1** [keon/algorithms#357]
hi, when i test combination.py, I found specific case with input large n, r too slow to find combination.

combination(50, 10) <- 10272278170 // too slow

in my opinion, using memoization method, can problem solving (using dictionary)

Can i send PR you?

**Comment by huseyindalbudak** [comment]
you can use factorial and combination function. 
https://github.com/huseyindalbudak/mathpy/blob/master/combination.py
the code is so faster for combination(50, 10) than keon algorithms
