### ISSUE TITLE
Logo/Icon

### ISSUE THREAD

**Issue by jbeguna04** [keon/algorithms#369]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by keon** [comment]
Of course! It would be awesome.
Please contact me or any other maintainers if you have any questions.
my email address is kwk236@gmail.com

**Comment by jbeguna04** [comment]
Thank you for your response. Hoping to propose my designs when it is ready. I would be priviledged to work with you

**Comment by EmmaMuhleman1** [comment]
Please tell me what you are thinking in terms of cost, as I have created my own site and it is half way decent (and I can add to it, I am just too busy right now)…

www.emc2partners.com


Sent from Mail for Windows 10

**Comment by jbeguna04** [comment]
![all](https://user-images.githubusercontent.com/35353768/42673816-ba71429a-869f-11e8-8e15-655d1e7887cd.png)

@keon , Greetings! Here are my designs about your project. What do you think?
Feel free to open some suggestions. Thank You!

**Comment by keon** [comment]
I love it! I love the logo that is shaped like python. :)
If possible could we change the typography to something that is immediately readable?
This is because there are many international users.

**Comment by jbeguna04** [comment]
Sure ill be sending more type of typography to you.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42731636-f2a39820-8843-11e8-972c-65d338ef4659.png)
Here are some types of typography

**Comment by ankit167** [comment]
+1 for the second one

- Ankit

**Comment by keon** [comment]
I vote for number 2 and 4

**Comment by jbeguna04** [comment]
@keon , Do you have to add more about the logo? Or I can upload the files and create a pull request to be needed in the project? What do you think?

**Comment by danghai** [comment]
+1

**Comment by goswami-rahul** [comment]
+1 for 3rd and 2nd icon.

**Comment by goswami-rahul** [comment]
pi

**Comment by jbeguna04** [comment]
@danghai , @goswami-rahul  Thank you!

**Comment by keon** [comment]
no. 2 seems to be the winner!
Feel free to make PR :)
@jbeguna04

**Comment by jbeguna04** [comment]
thank you @keon, Ill be making it now

**Comment by jbeguna04** [comment]
o

**Comment by jbeguna04** [comment]
Already created sir @keon , Hope you can check on it :)
https://github.com/keon/algorithms/pull/376
