### ISSUE TITLE
Tests : undesirable output on running tests

### ISSUE THREAD

**Issue by christianbender** [keon/algorithms#377]
If I run the tests with ```python3 -m unittest discover tests``` I get this:   

![screenshot](https://user-images.githubusercontent.com/23243382/42899836-87832bce-8ac7-11e8-844b-9d96958a29ce.png)  

I think it is an debug-print.
Can someone repeat it? My local repo is up-to-date.

**Comment by danghai** [comment]
@christianbender I fixed it!

**Comment by christianbender** [comment]
@danghai super!
