### ISSUE TITLE
longest non-repeat v1 issue

### ISSUE THREAD

**Issue by bmcculley** [keon/algorithms#388]
I'm wondering if `longest_non_repeat_v1` should be changed or taken off as it returns incorrect results in some cases.

**A couple of examples:**

"dvdf" should return 3 but v1 returns 2.

"asjrgapa" should return 6 but v1 returns 5

**Comment by danghai** [comment]
Hi @bmcculley could you point out the python file?

**Comment by bmcculley** [comment]
Hi @danghai, this is [the file](https://github.com/keon/algorithms/blob/master/algorithms/arrays/longest_non_repeat.py)

**Comment by danghai** [comment]
@bmcculley right. The algorithm is wrong.  Could you fix it (even `O(n^2)`)?

**Comment by danghai** [comment]
@bmcculley fix it. Thanks
