### ISSUE TITLE
Test fail. arrays/plus_one makes tests fail

### ISSUE THREAD

**Issue by krimvp** [keon/algorithms#431]
The function plus_one_v3() tries to access the index as if it was an actual index (number) but since it's being used in a for loop with an enumerate, it is actually a tuple of (idx,value) for all the items in the list

I discovered this while making a PR for another issue since it would reject my build.

Already making a PR changing it so the tests run again.

**Comment by keon** [comment]
@krimvp Thanks for the quick fix :)
