### ISSUE TITLE
the return value should be the last value

### ISSUE THREAD

**Issue by lifelifelife** [keon/algorithms#457]
https://github.com/keon/algorithms/blob/81d0e4d81ec55a0c9f5d5f9f7dcefe27e4f9db53/algorithms/arrays/longest_non_repeat.py#L60

use string "abccdefeab"，the last value is ‘’feab‘’,  but the return value is ‘’cdef‘’，the modify  in bellow:

            i = tmp.index(v)
            tmp = tmp[i+1:]

**Comment by ericklarac** [comment]
_cdef_ and _feab_ are valid answers, the algorithm returns the max length of the longest substring, in both cases the return value is 4.
