### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by HarsheetKakar** [keon/algorithms#468]
**Why?**
very important function used almost in every graphics application
**How?**
there is a simple O(n^3) solution (with possibility of Strassen's multiplication)
**Would I work on this issue**
yes

**Comment by goswami-rahul** [comment]
@HarsheetKakar you still working on this?

**Comment by HarsheetKakar** [comment]
Oh I forgot about that, you are welcome to take it if you want to

**Comment by youdymoo** [comment]
I'm looking into this feature now.

**Comment by HarsheetKakar** [comment]
Just add unittest and pr.is.good to.go

**Comment by youdymoo** [comment]
I don't think the former commit on this issue is a real implementation of Strassen's algorithm. It was an O(N^N) brute force algorithm. I'm trying to optimize it.

**Comment by HarsheetKakar** [comment]
Do it in as a different feature because stressen comes with its own set of issues
