### ISSUE TITLE
bfs/maze_search.py

### ISSUE THREAD

**Issue by EldanGS** [keon/algorithms#472]
https://github.com/keon/algorithms/blob/master/algorithms/bfs/maze_search.py

If you want to write in python, please keep Pythonic style.
In addition to that, please recalculate time and space complexity.

```
WHITE, BLACK = range(2)


def search_maze2(maze):
    if maze[0][0] == WHITE:
        return -1

    queue = [(0, 0, 0)]
    while queue:
        x, y, steps = queue.pop(0)
        maze[x][y] = WHITE
        if x == len(maze) and y == len(maze[0]):
            return steps

        for next_x, next_y in [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]:
            if (0 <= next_x < len(maze) and 0 <= next_y < len(maze[0])) \
                    and maze[next_x][next_y] == BLACK:
                queue.append((next_x, next_y, steps + 1))

    return -1

```

**Comment by goswami-rahul** [comment]
Thanks for pointing out! You may have noticed there still are some files which need refactoring. 
Please commit this refactor by opening a PR, I'll be happy to merge :)
If you wish, you can open PRs to refactor other files too.

**Comment by EldanGS** [comment]
Hi @goswami-rahul 

Sure, I will try to each week refactoring some algorithms if I will be available for coding.

Thanks for sharing good material, it will be helpful.

best regards,
[Eldan Abdrashim](http://linkedin.com/in/eldan-abdrashim-87aa27135/)
