### ISSUE TITLE
Complexity of algorithms

### ISSUE THREAD

**Issue by ankit167** [keon/algorithms#49]
There can be several approaches to solve a problem- the optimal, suboptimal or the brute force approach.
For an algorithm written in x.py, is it a good option to may be discuss the various approaches (write separate function in the file, for each approach)?, or just post the optimal solution?

The reason I brought this up is because, some algorithms in the repo have the optimal code written, while some do not. If a single solution to a problem is to be posted, then it would be good to stick to the optimal one across all files.

**Comment by newbazz** [comment]
hey @ankit167 i want to add a linter support in this project which will take care of the coding style. This is part of my winter project, can you guide me if i can take this issue up or not?

**Comment by goswami-rahul** [comment]
I think the more the approaches to the problem, the better. However, the complexity should be mentioned for each approach, as if will help compare among the optimal and other implementations.

**Comment by arihantjain124** [comment]
Hey, @ankit167 is this issue still relevant I would like to work on this I am just starting out to work on open source projects. Could you guide me? 
Thanks in advance
