### ISSUE TITLE
why Time complexity is O(n^2)

### ISSUE THREAD

**Issue by t2krew** [keon/algorithms#504]
https://github.com/keon/algorithms/blob/master/algorithms/arrays/delete_nth.py#L12

**Comment by snguyenthanh** [comment]
Because the [list.count](https://github.com/keon/algorithms/blob/master/algorithms/arrays/delete_nth.py#L16) method has to check every entry in the list, the runtime is going to be O(n).

**Comment by t2krew** [comment]
@snguyenthanh thanks
