### ISSUE TITLE
Complexity of delete_nth

### ISSUE THREAD

**Issue by vague369** [keon/algorithms#505]
How is the complexity of 'delete_nth' function O(n) if in python, the worst case for a dict lookup is O(n)?
https://wiki.python.org/moin/TimeComplexity

**Comment by GaryLai91** [comment]
I think because the hash table method just loops through the keys without deleting anything from the hash table.

**Comment by ericklarac** [comment]
By definition. the _amortized analysis_ considers both the costly and less costly operations together over the whole series of operations of the algorithm. Having said that, being strict about all the resources required for each operation of an algorithm, the operation can be considered as O(n) for the _amortized worst case_.

But if you assume the dictionary keys are drawn from a normal distribution and a robust hash function with no/little collisions, the operation takes O(1).
