### ISSUE TITLE
No name 'Iterable' in module 'collections'

### ISSUE THREAD

**Issue by RinatValiullov** [keon/algorithms#521]
https://github.com/keon/algorithms/blob/6f1fc9fadd76cb194183e98cc03587c30d93eb8e/algorithms/arrays/flatten.py#L6

My pylint can't find this module in `collections`:

`No name 'Iterable' in module 'collections'`

Got this warning:

![pycollect](https://user-images.githubusercontent.com/9755333/63664981-af5aa380-c7e2-11e9-9280-4f6dec7427b4.PNG)

**Comment by shubham1560** [comment]
it's just telling you that in future updates, this import would stop working, currently in your situation, the program must have worked fine

**Comment by RinatValiullov** [comment]
> it's just telling you that in future updates, this import would stop working, currently in your situation, the program must have worked fine

Is it mean that program is not cross-platform/ And not everyone could learn from your example? (Can you provide some comments or warning in the source for other developers like me?)

**Comment by goswami-rahul** [comment]
Thanks for pointing out. We need to import `Iterable` from `collections.abc` instead, to provide support for Python 3.8+.

**Comment by goswami-rahul** [comment]
Keeping this issue open until changes have been made.
