### ISSUE TITLE
Any plan to make it a python package?

### ISSUE THREAD

**Issue by zhyack** [keon/algorithms#53]
It seems that codes in this repo are more tutorials than tools. I wonder if there is any plan to convert the codes to efficient python apis?

**Comment by Aluriak** [comment]
The simpler way could be to put all directories containing code in a global `algorithms/` directory and create the setup.py accordingly. Instant upload garanteed.
(and it could also simplify a little the testing organization, see #29 )

The first problem : it already exists. [pypi](https://pypi.python.org/pypi/algorithms) and [github repo](https://github.com/nryoung/algorithms]. A solution could be to discuss with this other project, eventually merge them.

The second problem : the aim of this repo is above all to be a tutorial. Move all directories in a single one would lower the readability. Well, a solution is to create a more sophisticated setup.py.

**Comment by zhyack** [comment]
@Aluriak 
Clear enough for me. Thank you!

Maybe it's better to put the links into README.
