### ISSUE TITLE
More Maintainers Needed

### ISSUE THREAD

**Issue by keon** [keon/algorithms#580]
Currently, maintainers don't have much bandwidth to review PRs in timely manner.
I noticed that there's a long backlog of PRs that need to be reviewed and revised. 

I'd like to add a several more people who'd like to contribute to this project more directly by being maintainers.
There's no expectation of the maintainers in terms of contribution - you contribute as much as you like or as little as you like.

Please send an email to me (kwk236@gmail.com) if you are interested :)

Thanks
Keon

**Comment by lcw921** [comment]
I'd like to participate in this project with my team.
I sent a mail to you.
