### ISSUE TITLE
Add Maximum Flow Ford Fulkerson Algorithm

### ISSUE THREAD

**Issue by uniyalnitin** [keon/algorithms#595]
Please add the python implementation for For Fulkerson Algorithm, using DFS and BFS both approach

**Comment by DgrinderHZ** [comment]
Ok, I will join the contributors and put it on my to-do list!

**Comment by lcw921** [comment]
I have implemented Fulkerson Algorithm in Python using BFS. 
In the near future, i will be implementing Fulkerson Algorithm using DFS.
If this is what you want, please let me know.

[ADD] Create maximum_flow_bfs.py # 603

**Comment by lcw921** [comment]
I implemented the Ford Fulkerson Algorithm algorithm using both bfs and dfs. These are basically the same, but the only difference is whether they use queues or stacks as data structures to find the path.
If you need to implement a function rather than a data structure, please let me know.
