### ISSUE TITLE
@array/garage your math is wrong

### ISSUE THREAD

**Issue by Charlespoole** [keon/algorithms#61]
in the garage problem, when i set the initial = [1,2,3,4,0,5,6] and final = [1,6,0,4,5,3,2] ,in your math, the result is 7. But my math will use only require 5 steps to do it which are 
[1, 2, 3, 4, 5, 0, 6]
[1, 2, 0, 4, 5, 3, 6]
[1, 2, 6, 4, 5, 3, 0]
[1, 0, 6, 4, 5, 3, 2]
[1, 6, 0, 4, 5, 3, 2]

**Comment by samakshjain** [comment]
Can confirm this. 
You may play with my code on repl.it, [here](https://repl.it/Hz2u/latest) and the original [here](https://repl.it/Hz2x/latest).
