### ISSUE TITLE
Add Count Number of Connected Components in Graph

### ISSUE THREAD

**Issue by hardik-dadhich** [keon/algorithms#641]
Hi, Thanks for this Awesome Repo
Description :
Can we  Add Algorithm to find `Number of Connected components in Graph` in Algorithm/graph section?
please Let me know if there is a possibility of this.

**Comment by ericklarac** [comment]
@hardik-dadhich nice contribution. Feel free to add more algorithms on this repo.

**Comment by hardik-dadhich** [comment]
@ericklarac, Sure!
