### ISSUE TITLE
Path to Learn 

### ISSUE THREAD

**Issue by namangupta-98** [keon/algorithms#690]
Please could you please tell me from where I can learn complete data structures and algorithms to implement all these programs on my own.

**Comment by ericklarac** [comment]
For data structures, I think you can start with the [free course](https://www.udacity.com/course/data-structures-and-algorithms-in-python--ud513) from udacity, and some lessons from [leetcode](https://leetcode.com/explore/learn).

**Comment by namangupta-98** [comment]
and for algorithms.

**Comment by ericklarac** [comment]
The [MIT algorithms open course](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/) and [this book](http://jeffe.cs.illinois.edu/teaching/algorithms/) helped me

**Comment by namangupta-98** [comment]
ok, Thank You.

**Comment by Neha8942** [comment]
Buy a book data structure and algorithms by narasimha karumanchi this book is definately help you to learn data algorithms and it's easy to learn and understand.

**Comment by namangupta-98** [comment]
ok, thank you

**Comment by Neha8942** [comment]
🥰🥰🥰
