### ISSUE TITLE
No requirements.txt file

### ISSUE THREAD

**Issue by vanarpsharma** [keon/algorithms#72]
There should be a requirements.txt file given the python3 version being used

**Comment by Aluriak** [comment]
AFAIK, `requirements.txt` is not dedicated to used python version, but rather for [third-party library dependancies](https://pip.readthedocs.io/en/1.1/requirements.html).

**Comment by keon** [comment]
I think the only dependency is Python 3... right?

**Comment by keon** [comment]
Closing issue since this seems to be no problem
