### ISSUE TITLE
algorithms.map.longest_palindromic_subsequence     is incorrect.

### ISSUE THREAD

**Issue by kq58** [keon/algorithms#795]
algorithms.map.longest_palindromic_subsequence     is incorrect.

tests.test_map.TestLongestPalindromicSubsequence.test_longest_palindromic_subsequence_is_correct       is incorrect.

test.__init__.py      is incorrect.

**Comment by ericklarac** [comment]
@kq58 you can contribute adding the correct algorithm.

**Comment by kq58** [comment]
this could be an implementation of lps. it can return the logestSubStr as well.you can remove the '#' in the last line to do it.

> longest_palindromic_subsequence.py
def longest_palindromic_subsequence(s):
    
        k = len(s)
        olist = [0] * k    # 申请长度为n的列表，并初始化
        nList = [0] * k    # 同上
        logestSubStr = ""
        logestLen = 0
    
        for j in range(0, k):
            for i in range(0, j + 1):
                if j - i <= 1:
                    if s[i] == s[j]:
                        nList[i] = 1                 # 当 j 时，第 i 个子串为回文子串
                        len_t = j - i + 1
                        if logestLen < len_t:        # 判断长度
                            logestSubStr = s[i:j + 1]
                            logestLen = len_t
                else:
                    if s[i] == s[j] and olist[i+1]:   # 当j-i>1时，判断s[i]是否等于s[j]，并判断当j-1时，第i+1个子串是否为回文子串
                        nList[i] = 1                  # 当 j 时，第 i 个子串为回文子串
                        len_t = j - i + 1
                        if logestLen < len_t:
                            logestSubStr = s[i:j + 1]
                            logestLen = len_t
            olist = nList                            # 覆盖旧的列表
            nList = [0] * k                          # 新的列表清空
        # ~ from icecream import ic
        # ~ ic(s, logestSubStr)
        return logestLen#, logestSubStr

**Comment by kq58** [comment]
> @kq58 you can contribute adding the correct algorithm.

i'm a beginner too. i'll try my best.

**Comment by ericklarac** [comment]
Here's the right place to learn, check how to create PR on Github.

Then add your algorithm, and consider adding test cases.

**Comment by kq58** [comment]
@ericklarac  my internet sucks when viewing github or any other out_wall sites. i'll try to add some mline coments.

**Comment by ericklarac** [comment]
@kq58 no worries, I will merge for now.
